name: Sync Main to Other Branches

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Fetch all remote branches
      - name: Fetch all branches
        run: git fetch --all

      # Sync changes to develop branch
      - name: Merge into develop
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout develop
          git pull origin develop
          git merge --no-ff main
          git push origin develop
