name: Sync Main to Other Branches

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure Git user
      - name: Configure Git user
        run: |
          git config --global user.email "frugas@list.ru"
          git config --global user.name "fra1m"

      # Fetch all remote branches
      - name: Fetch all branches
        run: git fetch --all

      # Sync changes to develop branch
      - name: Merge into develop
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout develop
          git merge --allow-unrelated-histories --no-ff main
          git push origin/develop
